In [2]:
import numpy as np

In [2]:
# Create a 3X4X3 array with random values
example_array = np.arange(36).reshape(3,4,3)

print(example_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [3]:
# generate giant 1D array
np.random.seed(444)
giant_array = np.random.choice([False, True], size=100000)

# Count transitions without vectorization
def count_transitions(transitions_array)-> int:
    count = 0
    for i, j in zip(transitions_array[:-1], transitions_array[1:]):
        if j and not i:
            count += 1
    
    return count

print(f"Transitions count without vectorisation : {count_transitions(giant_array)}")

print(f"Transitions count with vectorisation : {np.count_nonzero(giant_array[:-1] < giant_array[1:])}")

# Intermezzo : Understanding Axes Notation
arr = np.array([[1, 2, 3],
                [10, 20, 30]])
print(f"Sum axis 0 : {arr.sum(axis=0)}")
print(f"Sum axis 1 : {arr.sum(axis=1)}")


Transitions count without vectorisation : 24984
Transitions count with vectorisation : 24984
Sum axis 0 : [11 22 33]
Sum axis 1 : [ 6 60]
