In [1]:
# Testing Jupter setup
import scipy

### Working With Vectors and Matrices Using NumPy

In [2]:
import numpy as np

In [10]:
# Creating arrays (ndarrays)

A = np.array([[1, 2], [3, 4], [5, 6]])
print(f"Array {A} is of type {A.dtype}")

A = np.array([[1.0, 2], [3, 4], [5, 6]])
print(f"Array {A} is of type {A.dtype}")

print(f"Shape of array {A} is {A.shape}")

print(f"Transpose of array {A} \n is \n {A.T}")
print(f"Shape of transposed array {A.T} is {A.T.shape}")

Array [[1 2]
 [3 4]
 [5 6]] is of type int64
Array [[1. 2.]
 [3. 4.]
 [5. 6.]] is of type float64
Shape of array [[1. 2.]
 [3. 4.]
 [5. 6.]] is (3, 2)
Transpose of array [[1. 2.]
 [3. 4.]
 [5. 6.]] 
 is 
 [[1. 3. 5.]
 [2. 4. 6.]]
Shape of transposed array [[1. 3. 5.]
 [2. 4. 6.]] is (2, 3)


In [19]:
# Creating vectors

# single dimensional vector
v = np.array([1, 2, 3])
print(f"Shape of vector \n {v} \n is \n {v.shape}")
print(f"Transpose of vector \n {v} \n is \n {v.T} (No effect)")

# 2 D vector
v = np.array([[1, 2, 3]])
print(f"Shape of vector \n {v} \n is \n {v.shape}")
print(f"Transpose of vector \n {v} \n is \n {v.T}")

# Use reshape to get a column vector from 1 D vector
v = np.array([1, 2, 3]).reshape(3,1)
print(f"Transpose of vector \n {v} \n is \n {v.T} ")
# Use reshape with -1 to avoid the rows parameter for column vector
v = np.array([1, 2, 3]).reshape(-1,1)
print(f"Shape of vector \n {v} \n is \n {v.shape} ")

Shape of vector 
 [1 2 3] 
 is 
 (3,)
Transpose of vector 
 [1 2 3] 
 is 
 [1 2 3] (No effect)
Shape of vector 
 [[1 2 3]] 
 is 
 (1, 3)
Transpose of vector 
 [[1 2 3]] 
 is 
 [[1]
 [2]
 [3]]
Transpose of vector 
 [[1]
 [2]
 [3]] 
 is 
 [[1 2 3]] 
Shape of vector 
 [[1]
 [2]
 [3]] 
 is 
 (3, 1) 


### Using Convenience Functions to Create Arrays

In [20]:
# Zeroes
print(np.zeros((3, 2)))


[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [21]:
# Ones
print(np.ones((3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
# Randoms - normal distribution
print(np.random.rand(3, 2))

[[0.1753066  0.79237299]
 [0.18790268 0.63840026]
 [0.30713908 0.27335764]]
